# Construindo banco de dados das amostras de vigas

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
import itertools
import numpy as np
import openpyxl
from parepy_toolbox import sampling_algorithm_structural_analysis
from obj import momento_limite_armadura_simples, area_aco_flexao_simples, momento_resistente_secao_sem_cor, obj_mestrado_victor

# Planejamento experimental

In [2]:
# Definindo os níveis das variáveis
h_levels = np.linspace(0.30, 0.70, 2)
b_levels = np.linspace(0.14, 0.35, 2)
f_levels = np.linspace(20000, 50000, 2)
divs = 2 # Levels for mechanical steel rate

# Gerando o planejamento fatorial completo com itertools.product
combinacoes = list(itertools.product(h_levels, b_levels, f_levels))

# Convertendo para DataFrame
df = pd.DataFrame(combinacoes, columns=['h', 'b_w', 'f_ck'])
df

     h   b_w     f_ck
0  0.3  0.14  20000.0
1  0.3  0.14  50000.0
2  0.3  0.35  20000.0
3  0.3  0.35  50000.0
4  0.7  0.14  20000.0
5  0.7  0.14  50000.0
6  0.7  0.35  20000.0
7  0.7  0.35  50000.0

# Criando o banco de armaduras

In [3]:
b_w = []
h = []
f_ck = []
m_rdlim = []
pho_s = []
a_s = []
for i in range(len(df)):
    b_w.append(df['b_w'][i])
    h.append(df['h'][i])
    f_ck.append(df['f_ck'][i])
    m_rdlim.append(momento_limite_armadura_simples(df['b_w'][i], df['h'][i], df['f_ck'][i]))
    a_saux, pho_saux = area_aco_flexao_simples(m_rdlim[i], df['b_w'][i], df['h'][i], df['f_ck'][i])
    pho_s.append(pho_saux)
    a_s.append(a_saux)

df['m_rdlim'] = m_rdlim
df['a_s'] = a_s
df['pho_s'] = pho_s
df

     h   b_w     f_ck      m_rdlim       a_s     pho_s
0  0.3  0.14  20000.0    36.584136  0.000380  0.904886
1  0.3  0.14  50000.0    91.460340  0.000950  2.262214
2  0.3  0.35  20000.0    91.460340  0.000950  0.904886
3  0.3  0.35  50000.0   228.650850  0.002375  2.262214
4  0.7  0.14  20000.0   199.180296  0.000887  0.904886
5  0.7  0.14  50000.0   497.950740  0.002217  2.262214
6  0.7  0.35  20000.0   497.950740  0.002217  0.904886
7  0.7  0.35  50000.0  1244.876850  0.005542  2.262214

# Subdividindo em grupos por classe de densidade de armadura

In [4]:
b_w = []
h = []
f_ck = []
m_rdlim = []
pho_s = []
a_s = []
for indece, linha in df.iterrows():
    aux = linha['pho_s'] / divs
    pho = 0
    for i in range(divs):
        pho += aux
        pho_s.append(pho)
        b_w.append(linha['b_w'])
        h.append(linha['h'])
        f_ck.append(linha['f_ck'])
        m_rdlim.append(linha['m_rdlim'])
        a_s.append(pho * linha['b_w'] * linha['h'] / 100)

df_aux = {'b_w': b_w, 'h': h, 'f_ck': f_ck, 'm_rdlim': m_rdlim, 'a_s': a_s, 'pho_s': pho_s}
df_aux = pd.DataFrame(df_aux)
df_aux['m_rd'] = df_aux.apply(lambda row: momento_resistente_secao_sem_cor(row['a_s'], row['b_w'], row['h'],row['f_ck']), axis=1)
df_aux

     b_w    h     f_ck      m_rdlim       a_s     pho_s         m_rd
0   0.14  0.3  20000.0    36.584136  0.000190  0.452443    22.998372
1   0.14  0.3  20000.0    36.584136  0.000380  0.904886    40.686467
2   0.14  0.3  50000.0    91.460340  0.000475  1.131107    57.495929
3   0.14  0.3  50000.0    91.460340  0.000950  2.262214   101.716167
4   0.35  0.3  20000.0    91.460340  0.000475  0.452443    57.495929
5   0.35  0.3  20000.0    91.460340  0.000950  0.904886   101.716167
6   0.35  0.3  50000.0   228.650850  0.001188  1.131107   143.739823
7   0.35  0.3  50000.0   228.650850  0.002375  2.262214   254.290418
8   0.14  0.7  20000.0   199.180296  0.000443  0.452443   125.213357
9   0.14  0.7  20000.0   199.180296  0.000887  0.904886   221.515208
10  0.14  0.7  50000.0   497.950740  0.001108  1.131107   313.033393
11  0.14  0.7  50000.0   497.950740  0.002217  2.262214   553.788021
12  0.35  0.7  20000.0   497.950740  0.001108  0.452443   313.033393
13  0.35  0.7  20000.0   497.950740  0.002217  0.904886   553.788021
14  0.35  0.7  50000.0  1244.876850  0.002771  1.131107   782.583482
15  0.35  0.7  50000.0  1244.876850  0.005542  2.262214  1384.470053

In [5]:
df_aux.drop(['m_rdlim'], axis='columns', inplace=True)
df_aux

     b_w    h     f_ck       a_s     pho_s         m_rd
0   0.14  0.3  20000.0  0.000190  0.452443    22.998372
1   0.14  0.3  20000.0  0.000380  0.904886    40.686467
2   0.14  0.3  50000.0  0.000475  1.131107    57.495929
3   0.14  0.3  50000.0  0.000950  2.262214   101.716167
4   0.35  0.3  20000.0  0.000475  0.452443    57.495929
5   0.35  0.3  20000.0  0.000950  0.904886   101.716167
6   0.35  0.3  50000.0  0.001188  1.131107   143.739823
7   0.35  0.3  50000.0  0.002375  2.262214   254.290418
8   0.14  0.7  20000.0  0.000443  0.452443   125.213357
9   0.14  0.7  20000.0  0.000887  0.904886   221.515208
10  0.14  0.7  50000.0  0.001108  1.131107   313.033393
11  0.14  0.7  50000.0  0.002217  2.262214   553.788021
12  0.35  0.7  20000.0  0.001108  0.452443   313.033393
13  0.35  0.7  20000.0  0.002217  0.904886   553.788021
14  0.35  0.7  50000.0  0.002771  1.131107   782.583482
15  0.35  0.7  50000.0  0.005542  2.262214  1384.470053

# Análise de confiabilidade no tempo

In [6]:
tempos = list(range(0, 101, 20))
beta = []
b_w_aux_list = []
h_aux_list = []
f_ck_aux_list = []
m_rd_aux_list = []
a_s_aux_list = []
mgk_aux_list = []
mqk_aux_list = []
time_aux_list = []
for i, row in df_aux.iterrows():
    b_w_aux = row['b_w']
    h_aux = row['h']
    f_ck_aux = row['f_ck']
    m_rd_aux = row['m_rd']
    a_s_aux = row['a_s']
    chi_list = list(np.linspace(0.15, 0.65, divs, endpoint=True))
    gamma_g = 1.40
    gamma_q = 1.40
    dados_viga = {'h (m)': h_aux, 'b_w (m)': b_w_aux, 'm_rd (kN.m)': m_rd_aux, 'a_s (m2)': a_s_aux, 'gamma_c': 1.00, 'gamma_s': 1.00, 'gamma_f': 1.00}
    none_variable = {'dados_viga': dados_viga, 'time analysis': tempos}

    for id, chi in enumerate(chi_list):
        den_g = gamma_g + gamma_q*chi/(1-chi)
        den_q = gamma_g*(1-chi)/chi + gamma_q
        m_gk = m_rd_aux/den_g
        m_qk = m_rd_aux/den_q

        # Data
        g = {'type': 'normal', 'parameters': {'mean': 1.06*m_gk, 'sigma': 0.12*1.06*m_gk}, 'stochastic variable': False}
        q = {'type': 'gumbel max', 'parameters': {'mean': 0.21*m_qk, 'sigma': 0.21*0.76*m_qk}, 'stochastic variable': True}
        f_ck = {'type': 'normal', 'parameters': {'mean': 1.22*f_ck_aux, 'sigma': 0.15*1.22*f_ck_aux}, 'stochastic variable': False}
        f_yk = {'type': 'normal', 'parameters': {'mean': 1.22*500000, 'sigma': 0.04*1.22*500000}, 'stochastic variable': False}
        teta_r = {'type': 'normal', 'parameters': {'mean': 1, 'sigma': 0.05}, 'stochastic variable': False}
        teta_s = {'type': 'normal', 'parameters': {'mean': 1, 'sigma': 0.05}, 'stochastic variable': False}
        var = [g, q, f_ck, f_yk, teta_r, teta_s]

        # PAREpy setup
        setup = {
                    'number of samples': 2500,
                    'numerical model': {'model sampling': 'mcs-time', 'time steps': len(none_variable['time analysis'])},
                    'variables settings': var,
                    'number of state limit functions or constraints': 1,
                    'none variable': none_variable,
                    'objective function': obj_mestrado_victor,
                    'name simulation': 'victor',
                }
        # Call algorithm
        results_aux, pf_aux, beta_aux = sampling_algorithm_structural_analysis(setup)
        pf_aux_aux = pf_aux['G_0'].tolist() # A função pf vira uma lista
        time_limit = -100 # Aqui vcs devem colocar a função de vcs
        b_w_aux_list.append(b_w_aux)
        h_aux_list.append(h_aux)
        f_ck_aux_list.append(f_ck_aux)
        m_rd_aux_list.append(m_rd_aux)
        mgk_aux_list.append(m_gk)
        mqk_aux_list.append(m_qk)
        a_s_aux_list.append(a_s_aux)
        time_aux_list.append(time_limit)
        
        # Supondo que você tenha um DataFrame chamado df_aux
        #results_aux.to_excel("df_aux.xlsx", index=False)

final_df = {
            'b_w': b_w_aux_list,
            'h': h_aux_list,
            'f_ck': f_ck_aux_list,
            'm_rd': m_rd_aux_list,
            'm_gk': mgk_aux_list,
            'm_qk': mqk_aux_list,
            'a_s': a_s_aux_list,
            'time': time_aux_list,
           }
final_df = pd.DataFrame(final_df)

11:23:41 - Checking inputs completed!
11:23:41 - Started State Limit Function evaluation (g)...
11:23:43 - Finished State Limit Function evaluation (g) in 2.61e+00 seconds!
11:23:43 - Started evaluation beta reliability index and failure probability...
11:23:43 - Finished evaluation beta reliability index and failure probability in 6.59e-02 seconds!
11:23:44 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112343.txt
11:23:44 - Checking inputs completed!
11:23:44 - Started State Limit Function evaluation (g)...
11:23:46 - Finished State Limit Function evaluation (g) in 2.62e+00 seconds!
11:23:46 - Started evaluation beta reliability index and failure probability...
11:23:46 - Finished evaluation beta reliability index and failure probability in 9.90e-02 seconds!
11:23:46 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112346.txt
11:23:46 - Checking inputs completed!
11:23:46 - Started State Limit Function evaluation (g)...
11:23:49 - Finished State Limit Function evaluation (g) in 2.80e+00 seconds!
11:23:49 - Started evaluation beta reliability index and failure probability...
11:23:49 - Finished evaluation beta reliability index and failure probability in 7.96e-02 seconds!
11:23:50 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112349.txt
11:23:50 - Checking inputs completed!
11:23:50 - Started State Limit Function evaluation (g)...
11:23:52 - Finished State Limit Function evaluation (g) in 2.79e+00 seconds!
11:23:52 - Started evaluation beta reliability index and failure probability...
11:23:52 - Finished evaluation beta reliability index and failure probability in 9.86e-02 seconds!
11:23:53 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112352.txt
11:23:53 - Checking inputs completed!
11:23:53 - Started State Limit Function evaluation (g)...
11:23:55 - Finished State Limit Function evaluation (g) in 2.79e+00 seconds!
11:23:55 - Started evaluation beta reliability index and failure probability...
11:23:55 - Finished evaluation beta reliability index and failure probability in 6.69e-02 seconds!
11:23:56 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112355.txt
11:23:56 - Checking inputs completed!
11:23:56 - Started State Limit Function evaluation (g)...
11:23:58 - Finished State Limit Function evaluation (g) in 2.67e+00 seconds!
11:23:58 - Started evaluation beta reliability index and failure probability...
11:23:58 - Finished evaluation beta reliability index and failure probability in 8.61e-02 seconds!
11:23:59 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112358.txt
11:23:59 - Checking inputs completed!
11:23:59 - Started State Limit Function evaluation (g)...
11:24:02 - Finished State Limit Function evaluation (g) in 3.16e+00 seconds!
11:24:02 - Started evaluation beta reliability index and failure probability...
11:24:02 - Finished evaluation beta reliability index and failure probability in 6.84e-02 seconds!
11:24:02 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112402.txt
11:24:02 - Checking inputs completed!
11:24:02 - Started State Limit Function evaluation (g)...
11:24:05 - Finished State Limit Function evaluation (g) in 3.20e+00 seconds!
11:24:05 - Started evaluation beta reliability index and failure probability...
11:24:05 - Finished evaluation beta reliability index and failure probability in 9.99e-02 seconds!
11:24:06 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112405.txt
11:24:06 - Checking inputs completed!
11:24:06 - Started State Limit Function evaluation (g)...
11:24:09 - Finished State Limit Function evaluation (g) in 3.13e+00 seconds!
11:24:09 - Started evaluation beta reliability index and failure probability...
11:24:09 - Finished evaluation beta reliability index and failure probability in 6.79e-02 seconds!
11:24:09 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112409.txt
11:24:09 - Checking inputs completed!
11:24:09 - Started State Limit Function evaluation (g)...
11:24:12 - Finished State Limit Function evaluation (g) in 2.95e+00 seconds!
11:24:12 - Started evaluation beta reliability index and failure probability...
11:24:12 - Finished evaluation beta reliability index and failure probability in 8.94e-02 seconds!
11:24:12 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112412.txt
11:24:12 - Checking inputs completed!
11:24:12 - Started State Limit Function evaluation (g)...
11:24:15 - Finished State Limit Function evaluation (g) in 2.78e+00 seconds!
11:24:15 - Started evaluation beta reliability index and failure probability...
11:24:15 - Finished evaluation beta reliability index and failure probability in 8.09e-02 seconds!
11:24:15 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112415.txt
11:24:15 - Checking inputs completed!
11:24:15 - Started State Limit Function evaluation (g)...
11:24:18 - Finished State Limit Function evaluation (g) in 2.81e+00 seconds!
11:24:18 - Started evaluation beta reliability index and failure probability...
11:24:18 - Finished evaluation beta reliability index and failure probability in 9.17e-02 seconds!
11:24:18 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112418.txt
11:24:18 - Checking inputs completed!
11:24:18 - Started State Limit Function evaluation (g)...
11:24:21 - Finished State Limit Function evaluation (g) in 2.93e+00 seconds!
11:24:21 - Started evaluation beta reliability index and failure probability...
11:24:21 - Finished evaluation beta reliability index and failure probability in 6.91e-02 seconds!
11:24:22 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112421.txt
11:24:22 - Checking inputs completed!
11:24:22 - Started State Limit Function evaluation (g)...
11:24:25 - Finished State Limit Function evaluation (g) in 3.15e+00 seconds!
11:24:25 - Started evaluation beta reliability index and failure probability...
11:24:25 - Finished evaluation beta reliability index and failure probability in 9.25e-02 seconds!
11:24:25 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112425.txt
11:24:25 - Checking inputs completed!
11:24:25 - Started State Limit Function evaluation (g)...
11:24:28 - Finished State Limit Function evaluation (g) in 2.70e+00 seconds!
11:24:28 - Started evaluation beta reliability index and failure probability...
11:24:28 - Finished evaluation beta reliability index and failure probability in 7.04e-02 seconds!
11:24:28 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112428.txt
11:24:28 - Checking inputs completed!
11:24:28 - Started State Limit Function evaluation (g)...
11:24:31 - Finished State Limit Function evaluation (g) in 2.97e+00 seconds!
11:24:31 - Started evaluation beta reliability index and failure probability...
11:24:31 - Finished evaluation beta reliability index and failure probability in 8.81e-02 seconds!
11:24:31 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112431.txt
11:24:31 - Checking inputs completed!
11:24:31 - Started State Limit Function evaluation (g)...
11:24:34 - Finished State Limit Function evaluation (g) in 2.68e+00 seconds!
11:24:34 - Started evaluation beta reliability index and failure probability...
11:24:34 - Finished evaluation beta reliability index and failure probability in 6.75e-02 seconds!
11:24:34 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112434.txt
11:24:34 - Checking inputs completed!
11:24:34 - Started State Limit Function evaluation (g)...
11:24:37 - Finished State Limit Function evaluation (g) in 2.71e+00 seconds!
11:24:37 - Started evaluation beta reliability index and failure probability...
11:24:37 - Finished evaluation beta reliability index and failure probability in 8.36e-02 seconds!
11:24:37 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112437.txt
11:24:37 - Checking inputs completed!
11:24:37 - Started State Limit Function evaluation (g)...
11:24:40 - Finished State Limit Function evaluation (g) in 2.63e+00 seconds!
11:24:40 - Started evaluation beta reliability index and failure probability...
11:24:40 - Finished evaluation beta reliability index and failure probability in 8.07e-02 seconds!
11:24:40 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112440.txt
11:24:40 - Checking inputs completed!
11:24:40 - Started State Limit Function evaluation (g)...
11:24:43 - Finished State Limit Function evaluation (g) in 3.16e+00 seconds!
11:24:43 - Started evaluation beta reliability index and failure probability...
11:24:43 - Finished evaluation beta reliability index and failure probability in 8.94e-02 seconds!
11:24:44 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112443.txt
11:24:44 - Checking inputs completed!
11:24:44 - Started State Limit Function evaluation (g)...
11:24:46 - Finished State Limit Function evaluation (g) in 2.75e+00 seconds!
11:24:46 - Started evaluation beta reliability index and failure probability...
11:24:46 - Finished evaluation beta reliability index and failure probability in 6.80e-02 seconds!
11:24:47 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112446.txt
11:24:47 - Checking inputs completed!
11:24:47 - Started State Limit Function evaluation (g)...
11:24:49 - Finished State Limit Function evaluation (g) in 2.71e+00 seconds!
11:24:49 - Started evaluation beta reliability index and failure probability...
11:24:49 - Finished evaluation beta reliability index and failure probability in 9.08e-02 seconds!
11:24:50 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112449.txt
11:24:50 - Checking inputs completed!
11:24:50 - Started State Limit Function evaluation (g)...
11:24:53 - Finished State Limit Function evaluation (g) in 3.07e+00 seconds!
11:24:53 - Started evaluation beta reliability index and failure probability...
11:24:53 - Finished evaluation beta reliability index and failure probability in 8.35e-02 seconds!
11:24:53 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112453.txt
11:24:53 - Checking inputs completed!
11:24:53 - Started State Limit Function evaluation (g)...
11:24:56 - Finished State Limit Function evaluation (g) in 2.73e+00 seconds!
11:24:56 - Started evaluation beta reliability index and failure probability...
11:24:56 - Finished evaluation beta reliability index and failure probability in 8.17e-02 seconds!
11:24:56 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112456.txt
11:24:56 - Checking inputs completed!
11:24:56 - Started State Limit Function evaluation (g)...
11:24:59 - Finished State Limit Function evaluation (g) in 2.59e+00 seconds!
11:24:59 - Started evaluation beta reliability index and failure probability...
11:24:59 - Finished evaluation beta reliability index and failure probability in 6.67e-02 seconds!
11:24:59 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112459.txt
11:24:59 - Checking inputs completed!
11:24:59 - Started State Limit Function evaluation (g)...
11:25:02 - Finished State Limit Function evaluation (g) in 2.94e+00 seconds!
11:25:02 - Started evaluation beta reliability index and failure probability...
11:25:02 - Finished evaluation beta reliability index and failure probability in 8.62e-02 seconds!
11:25:02 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112502.txt
11:25:02 - Checking inputs completed!
11:25:02 - Started State Limit Function evaluation (g)...
11:25:05 - Finished State Limit Function evaluation (g) in 2.94e+00 seconds!
11:25:05 - Started evaluation beta reliability index and failure probability...
11:25:05 - Finished evaluation beta reliability index and failure probability in 7.92e-02 seconds!
11:25:06 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112505.txt
11:25:06 - Checking inputs completed!
11:25:06 - Started State Limit Function evaluation (g)...
11:25:08 - Finished State Limit Function evaluation (g) in 2.88e+00 seconds!
11:25:08 - Started evaluation beta reliability index and failure probability...
11:25:08 - Finished evaluation beta reliability index and failure probability in 8.67e-02 seconds!
11:25:09 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112508.txt
11:25:09 - Checking inputs completed!
11:25:09 - Started State Limit Function evaluation (g)...
11:25:12 - Finished State Limit Function evaluation (g) in 3.16e+00 seconds!
11:25:12 - Started evaluation beta reliability index and failure probability...
11:25:12 - Finished evaluation beta reliability index and failure probability in 6.98e-02 seconds!
11:25:12 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112512.txt
11:25:12 - Checking inputs completed!
11:25:12 - Started State Limit Function evaluation (g)...
11:25:15 - Finished State Limit Function evaluation (g) in 2.78e+00 seconds!
11:25:15 - Started evaluation beta reliability index and failure probability...
11:25:15 - Finished evaluation beta reliability index and failure probability in 8.34e-02 seconds!
11:25:15 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112515.txt
11:25:15 - Checking inputs completed!
11:25:15 - Started State Limit Function evaluation (g)...
11:25:18 - Finished State Limit Function evaluation (g) in 2.66e+00 seconds!
11:25:18 - Started evaluation beta reliability index and failure probability...
11:25:18 - Finished evaluation beta reliability index and failure probability in 8.07e-02 seconds!
11:25:18 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112518.txt
11:25:18 - Checking inputs completed!
11:25:18 - Started State Limit Function evaluation (g)...
11:25:21 - Finished State Limit Function evaluation (g) in 2.81e+00 seconds!
11:25:21 - Started evaluation beta reliability index and failure probability...
11:25:21 - Finished evaluation beta reliability index and failure probability in 1.00e-01 seconds!
11:25:21 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-112521.txt

In [7]:
final_df.to_excel("final_df_tempo_limite.xlsx", index=False)

In [8]:
final_df.head(20)

     b_w    h     f_ck        m_rd        m_gk        m_qk       a_s  time
0   0.14  0.3  20000.0   22.998372   13.963297    2.464111  0.000190  -100
1   0.14  0.3  20000.0   22.998372    5.749593   10.677815  0.000190  -100
2   0.14  0.3  20000.0   40.686467   24.702498    4.359264  0.000380  -100
3   0.14  0.3  20000.0   40.686467   10.171617   18.890145  0.000380  -100
4   0.14  0.3  50000.0   57.495929   34.908243    6.160278  0.000475  -100
5   0.14  0.3  50000.0   57.495929   14.373982   26.694539  0.000475  -100
6   0.14  0.3  50000.0  101.716167   61.756244   10.898161  0.000950  -100
7   0.14  0.3  50000.0  101.716167   25.429042   47.225363  0.000950  -100
8   0.35  0.3  20000.0   57.495929   34.908243    6.160278  0.000475  -100
9   0.35  0.3  20000.0   57.495929   14.373982   26.694539  0.000475  -100
10  0.35  0.3  20000.0  101.716167   61.756244   10.898161  0.000950  -100
11  0.35  0.3  20000.0  101.716167   25.429042   47.225363  0.000950  -100
12  0.35  0.3  50000.0  143.739823   87.270607   15.400695  0.001188  -100
13  0.35  0.3  50000.0  143.739823   35.934956   66.736346  0.001188  -100
14  0.35  0.3  50000.0  254.290418  154.390611   27.245402  0.002375  -100
15  0.35  0.3  50000.0  254.290418   63.572604  118.063408  0.002375  -100
16  0.14  0.7  20000.0  125.213357   76.022395   13.415717  0.000443  -100
17  0.14  0.7  20000.0  125.213357   31.303339   58.134773  0.000443  -100
18  0.14  0.7  20000.0  221.515208  134.491377   23.733772  0.000887  -100
19  0.14  0.7  20000.0  221.515208   55.378802  102.846347  0.000887  -100