# Construindo banco de dados das amostras de vigas

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
import itertools
import numpy as np
from parepy_toolbox import sampling_algorithm_structural_analysis
from obj import momento_limite_armadura_simples, area_aco_flexao_simples, momento_resistente_secao_sem_cor, obj_mestrado_victor, verifica_tempo_limite

# Planejamento experimental

In [2]:
# Definindo os níveis das variáveis
divs = 5
n_levels = 5
n_times = 5
h_levels = np.linspace(0.30, 0.70, n_levels)
b_levels = np.linspace(0.14, 0.35, n_levels)
f_levels = np.linspace(20000, 50000, n_levels)
combinacoes = list(itertools.product(h_levels, b_levels, f_levels))
df = pd.DataFrame(combinacoes, columns=['h', 'b_w', 'f_ck'])
df

       h   b_w     f_ck
0    0.3  0.14  20000.0
1    0.3  0.14  27500.0
2    0.3  0.14  35000.0
3    0.3  0.14  42500.0
4    0.3  0.14  50000.0
..   ...   ...      ...
120  0.7  0.35  20000.0
121  0.7  0.35  27500.0
122  0.7  0.35  35000.0
123  0.7  0.35  42500.0
124  0.7  0.35  50000.0

[125 rows x 3 columns]

# Criando o banco de armaduras

In [3]:
b_w = []
h = []
f_ck = []
m_rdlim = []
pho_s = []
a_s = []
for i in range(len(df)):
    b_w.append(df['b_w'][i])
    h.append(df['h'][i])
    f_ck.append(df['f_ck'][i])
    m_rdlim.append(momento_limite_armadura_simples(df['b_w'][i], df['h'][i], df['f_ck'][i]))
    a_saux, pho_saux = area_aco_flexao_simples(m_rdlim[i], df['b_w'][i], df['h'][i], df['f_ck'][i])
    pho_s.append(pho_saux)
    a_s.append(a_saux)

df['m_rdlim'] = m_rdlim
df['a_s'] = a_s
df['pho_s'] = pho_s
df

       h   b_w     f_ck      m_rdlim       a_s     pho_s
0    0.3  0.14  20000.0    36.584136  0.000380  0.904886
1    0.3  0.14  27500.0    50.303187  0.000523  1.244218
2    0.3  0.14  35000.0    64.022238  0.000665  1.583550
3    0.3  0.14  42500.0    77.741289  0.000808  1.922882
4    0.3  0.14  50000.0    91.460340  0.000950  2.262214
..   ...   ...      ...          ...       ...       ...
120  0.7  0.35  20000.0   497.950740  0.002217  0.904886
121  0.7  0.35  27500.0   684.682268  0.003048  1.244218
122  0.7  0.35  35000.0   871.413795  0.003880  1.583550
123  0.7  0.35  42500.0  1058.145323  0.004711  1.922882
124  0.7  0.35  50000.0  1244.876850  0.005542  2.262214

[125 rows x 6 columns]

# Subdividindo em grupos por classe de densidade de armadura

In [4]:
b_w = []
h = []
f_ck = []
m_rdlim = []
pho_s = []
a_s = []
for indece, linha in df.iterrows():
    aux = linha['pho_s'] / divs
    pho = 0
    for i in range(divs):
        pho += aux
        pho_s.append(pho)
        b_w.append(linha['b_w'])
        h.append(linha['h'])
        f_ck.append(linha['f_ck'])
        m_rdlim.append(linha['m_rdlim'])
        a_s.append(pho * linha['b_w'] * linha['h'] / 100)

df_aux = {'b_w': b_w, 'h': h, 'f_ck': f_ck, 'm_rdlim': m_rdlim, 'a_s': a_s, 'pho_s': pho_s}
df_aux = pd.DataFrame(df_aux)
df_aux['m_rd'] = df_aux.apply(lambda row: momento_resistente_secao_sem_cor(row['a_s'], row['b_w'], row['h'],row['f_ck']), axis=1)
df_aux

      b_w    h     f_ck      m_rdlim       a_s     pho_s         m_rd
0    0.14  0.3  20000.0    36.584136  0.000076  0.180977     9.836582
1    0.14  0.3  20000.0    36.584136  0.000152  0.361954    18.823519
2    0.14  0.3  20000.0    36.584136  0.000228  0.542931    26.960813
3    0.14  0.3  20000.0    36.584136  0.000304  0.723909    34.248462
4    0.14  0.3  20000.0    36.584136  0.000380  0.904886    40.686467
..    ...  ...      ...          ...       ...       ...          ...
620  0.35  0.7  50000.0  1244.876850  0.001108  0.452443   334.717022
621  0.35  0.7  50000.0  1244.876850  0.002217  0.904886   640.522538
622  0.35  0.7  50000.0  1244.876850  0.003325  1.357329   917.416549
623  0.35  0.7  50000.0  1244.876850  0.004434  1.809771  1165.399054
624  0.35  0.7  50000.0  1244.876850  0.005542  2.262214  1384.470053

[625 rows x 7 columns]

In [5]:
df_aux.drop(['m_rdlim'], axis='columns', inplace=True)
df_aux

      b_w    h     f_ck       a_s     pho_s         m_rd
0    0.14  0.3  20000.0  0.000076  0.180977     9.836582
1    0.14  0.3  20000.0  0.000152  0.361954    18.823519
2    0.14  0.3  20000.0  0.000228  0.542931    26.960813
3    0.14  0.3  20000.0  0.000304  0.723909    34.248462
4    0.14  0.3  20000.0  0.000380  0.904886    40.686467
..    ...  ...      ...       ...       ...          ...
620  0.35  0.7  50000.0  0.001108  0.452443   334.717022
621  0.35  0.7  50000.0  0.002217  0.904886   640.522538
622  0.35  0.7  50000.0  0.003325  1.357329   917.416549
623  0.35  0.7  50000.0  0.004434  1.809771  1165.399054
624  0.35  0.7  50000.0  0.005542  2.262214  1384.470053

[625 rows x 6 columns]

# Análise de confiabilidade no tempo

In [6]:
tempos = list(range(0, 101, n_times))
beta = []
b_w_aux_list = []
h_aux_list = []
f_ck_aux_list = []
m_rd_aux_list = []
a_s_aux_list = []
mgk_aux_list = []
mqk_aux_list = []
time_aux_list = []
for i, row in df_aux.iterrows():
    b_w_aux = row['b_w']
    h_aux = row['h']
    f_ck_aux = row['f_ck']
    m_rd_aux = row['m_rd']
    a_s_aux = row['a_s']
    chi_list = list(np.linspace(0.10, 0.60, divs, endpoint=True))
    gamma_g = 1.40
    gamma_q = 1.40
    dados_viga = {'h (m)': h_aux, 'b_w (m)': b_w_aux, 'm_rd (kN.m)': m_rd_aux, 'a_s (m2)': a_s_aux, 'gamma_c': 1.00, 'gamma_s': 1.00, 'gamma_f': 1.00}
    none_variable = {'dados_viga': dados_viga, 'time analysis': tempos}

    for id, chi in enumerate(chi_list):
        den_g = gamma_g + gamma_q*chi/(1-chi)
        den_q = gamma_g*(1-chi)/chi + gamma_q
        m_gk = m_rd_aux/den_g
        m_qk = m_rd_aux/den_q

        # Data
        g = {'type': 'normal', 'parameters': {'mean': 1.06*m_gk, 'sigma': 0.12*1.06*m_gk}, 'stochastic variable': False}
        q = {'type': 'gumbel max', 'parameters': {'mean': 0.21*m_qk, 'sigma': 0.21*0.76*m_qk}, 'stochastic variable': True}
        f_ck = {'type': 'normal', 'parameters': {'mean': 1.22*f_ck_aux, 'sigma': 0.15*1.22*f_ck_aux}, 'stochastic variable': False}
        f_yk = {'type': 'normal', 'parameters': {'mean': 1.22*500000, 'sigma': 0.04*1.22*500000}, 'stochastic variable': False}
        teta_r = {'type': 'normal', 'parameters': {'mean': 1, 'sigma': 0.05}, 'stochastic variable': False}
        teta_s = {'type': 'normal', 'parameters': {'mean': 1, 'sigma': 0.05}, 'stochastic variable': False}
        var = [g, q, f_ck, f_yk, teta_r, teta_s]

        # PAREpy setup
        setup = {
                    'number of samples': 40000,
                    'numerical model': {'model sampling': 'lhs-time', 'time steps': len(none_variable['time analysis'])},
                    'variables settings': var,
                    'number of state limit functions or constraints': 1,
                    'none variable': none_variable,
                    'objective function': obj_mestrado_victor,
                    'name simulation': None,
                }
        # Call algorithm
        results_aux, pf_aux, beta_aux = sampling_algorithm_structural_analysis(setup)
        pf_aux_aux = pf_aux['G_0'].tolist()
        time_limit = verifica_tempo_limite(pf_aux_aux, tempos, pf_limit=6.87138E-4)
        b_w_aux_list.append(b_w_aux)
        h_aux_list.append(h_aux)
        f_ck_aux_list.append(f_ck_aux)
        m_rd_aux_list.append(m_rd_aux)
        mgk_aux_list.append(m_gk)
        mqk_aux_list.append(m_qk)
        a_s_aux_list.append(a_s_aux)
        time_aux_list.append(time_limit)
        
        # Supondo que você tenha um DataFrame chamado df_aux
        #results_aux.to_excel("df_aux.xlsx", index=False)

final_df = {
            'b_w': b_w_aux_list,
            'h': h_aux_list,
            'f_ck': f_ck_aux_list,
            'm_rd': m_rd_aux_list,
            'm_gk': mgk_aux_list,
            'm_qk': mqk_aux_list,
            'a_s': a_s_aux_list,
            'time': time_aux_list,
           }
final_df = pd.DataFrame(final_df)

00:08:37 - Checking inputs completed!
00:08:37 - Started State Limit Function evaluation (g)...
00:08:51 - Finished State Limit Function evaluation (g) in 1.40e+01 seconds!
00:08:51 - Started evaluation beta reliability index and failure probability...
00:08:51 - Finished evaluation beta reliability index and failure probability in 7.11e-02 seconds!
00:08:51 - Voilà!!!!....simulation results were not saved in a text file!
00:08:51 - Checking inputs completed!
00:08:51 - Started State Limit Function evaluation (g)...
00:09:05 - Finished State Limit Function evaluation (g) in 1.40e+01 seconds!
00:09:05 - Started evaluation beta reliability index and failure probability...
00:09:06 - Finished evaluation beta reliability index and failure probability in 1.38e-01 seconds!
00:09:06 - Voilà!!!!....simulation results were not saved in a text file!
00:09:06 - Checking inputs completed!
00:09:06 - Started State Limit Function evaluation (g)...
00:09:19 - Finished State Limit Function evaluation (g) in 1.37e+01 seconds!
00:09:19 - Started evaluation beta reliability index and failure probability...
00:09:19 - Finished evaluation beta reliability index and failure probability in 1.90e-01 seconds!
00:09:19 - Voilà!!!!....simulation results were not saved in a text file!
00:09:20 - Checking inputs completed!
00:09:20 - Started State Limit Function evaluation (g)...
00:09:33 - Finished State Limit Function evaluation (g) in 1.36e+01 seconds!
00:09:33 - Started evaluation beta reliability index and failure probability...
00:09:33 - Finished evaluation beta reliability index and failure probability in 1.83e-01 seconds!
00:09:33 - Voilà!!!!....simulation results were not saved in a text file!
00:09:33 - Checking inputs completed!
00:09:33 - Started State Limit Function evaluation (g)...
00:09:47 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:09:47 - Started evaluation beta reliability index and failure probability...
00:09:47 - Finished evaluation beta reliability index and failure probability in 2.05e-01 seconds!
00:09:47 - Voilà!!!!....simulation results were not saved in a text file!
00:09:47 - Checking inputs completed!
00:09:47 - Started State Limit Function evaluation (g)...
00:10:00 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:10:00 - Started evaluation beta reliability index and failure probability...
00:10:00 - Finished evaluation beta reliability index and failure probability in 1.33e-01 seconds!
00:10:00 - Voilà!!!!....simulation results were not saved in a text file!
00:10:00 - Checking inputs completed!
00:10:00 - Started State Limit Function evaluation (g)...
00:10:14 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:10:14 - Started evaluation beta reliability index and failure probability...
00:10:14 - Finished evaluation beta reliability index and failure probability in 1.73e-01 seconds!
00:10:14 - Voilà!!!!....simulation results were not saved in a text file!
00:10:14 - Checking inputs completed!
00:10:14 - Started State Limit Function evaluation (g)...
00:10:27 - Finished State Limit Function evaluation (g) in 1.34e+01 seconds!
00:10:27 - Started evaluation beta reliability index and failure probability...
00:10:28 - Finished evaluation beta reliability index and failure probability in 1.90e-01 seconds!
00:10:28 - Voilà!!!!....simulation results were not saved in a text file!
00:10:28 - Checking inputs completed!
00:10:28 - Started State Limit Function evaluation (g)...
00:10:41 - Finished State Limit Function evaluation (g) in 1.34e+01 seconds!
00:10:41 - Started evaluation beta reliability index and failure probability...
00:10:41 - Finished evaluation beta reliability index and failure probability in 1.93e-01 seconds!
00:10:41 - Voilà!!!!....simulation results were not saved in a text file!
00:10:41 - Checking inputs completed!
00:10:41 - Started State Limit Function evaluation (g)...
00:10:55 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:10:55 - Started evaluation beta reliability index and failure probability...
00:10:55 - Finished evaluation beta reliability index and failure probability in 1.97e-01 seconds!
00:10:55 - Voilà!!!!....simulation results were not saved in a text file!
00:10:55 - Checking inputs completed!
00:10:55 - Started State Limit Function evaluation (g)...
00:11:08 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:11:08 - Started evaluation beta reliability index and failure probability...
00:11:08 - Finished evaluation beta reliability index and failure probability in 1.33e-01 seconds!
00:11:08 - Voilà!!!!....simulation results were not saved in a text file!
00:11:08 - Checking inputs completed!
00:11:08 - Started State Limit Function evaluation (g)...
00:11:22 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:11:22 - Started evaluation beta reliability index and failure probability...
00:11:22 - Finished evaluation beta reliability index and failure probability in 1.78e-01 seconds!
00:11:22 - Voilà!!!!....simulation results were not saved in a text file!
00:11:22 - Checking inputs completed!
00:11:22 - Started State Limit Function evaluation (g)...
00:11:35 - Finished State Limit Function evaluation (g) in 1.32e+01 seconds!
00:11:35 - Started evaluation beta reliability index and failure probability...
00:11:35 - Finished evaluation beta reliability index and failure probability in 1.99e-01 seconds!
00:11:35 - Voilà!!!!....simulation results were not saved in a text file!
00:11:35 - Checking inputs completed!
00:11:35 - Started State Limit Function evaluation (g)...
00:11:49 - Finished State Limit Function evaluation (g) in 1.34e+01 seconds!
00:11:49 - Started evaluation beta reliability index and failure probability...
00:11:49 - Finished evaluation beta reliability index and failure probability in 2.03e-01 seconds!
00:11:49 - Voilà!!!!....simulation results were not saved in a text file!
00:11:49 - Checking inputs completed!
00:11:49 - Started State Limit Function evaluation (g)...
00:12:02 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:12:02 - Started evaluation beta reliability index and failure probability...
00:12:02 - Finished evaluation beta reliability index and failure probability in 2.02e-01 seconds!
00:12:02 - Voilà!!!!....simulation results were not saved in a text file!
00:12:02 - Checking inputs completed!
00:12:02 - Started State Limit Function evaluation (g)...
00:12:16 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:12:16 - Started evaluation beta reliability index and failure probability...
00:12:16 - Finished evaluation beta reliability index and failure probability in 1.33e-01 seconds!
00:12:16 - Voilà!!!!....simulation results were not saved in a text file!
00:12:16 - Checking inputs completed!
00:12:16 - Started State Limit Function evaluation (g)...
00:12:29 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:12:29 - Started evaluation beta reliability index and failure probability...
00:12:29 - Finished evaluation beta reliability index and failure probability in 1.76e-01 seconds!
00:12:29 - Voilà!!!!....simulation results were not saved in a text file!
00:12:29 - Checking inputs completed!
00:12:29 - Started State Limit Function evaluation (g)...
00:12:43 - Finished State Limit Function evaluation (g) in 1.34e+01 seconds!
00:12:43 - Started evaluation beta reliability index and failure probability...
00:12:43 - Finished evaluation beta reliability index and failure probability in 1.98e-01 seconds!
00:12:43 - Voilà!!!!....simulation results were not saved in a text file!
00:12:43 - Checking inputs completed!
00:12:43 - Started State Limit Function evaluation (g)...
00:12:56 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:12:56 - Started evaluation beta reliability index and failure probability...
00:12:57 - Finished evaluation beta reliability index and failure probability in 2.03e-01 seconds!
00:12:57 - Voilà!!!!....simulation results were not saved in a text file!
00:12:57 - Checking inputs completed!
00:12:57 - Started State Limit Function evaluation (g)...
00:13:10 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:13:10 - Started evaluation beta reliability index and failure probability...
00:13:10 - Finished evaluation beta reliability index and failure probability in 2.13e-01 seconds!
00:13:10 - Voilà!!!!....simulation results were not saved in a text file!
00:13:10 - Checking inputs completed!
00:13:10 - Started State Limit Function evaluation (g)...
00:13:24 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:13:24 - Started evaluation beta reliability index and failure probability...
00:13:24 - Finished evaluation beta reliability index and failure probability in 7.55e-02 seconds!
00:13:24 - Voilà!!!!....simulation results were not saved in a text file!
00:13:24 - Checking inputs completed!
00:13:24 - Started State Limit Function evaluation (g)...
00:13:37 - Finished State Limit Function evaluation (g) in 1.34e+01 seconds!
00:13:37 - Started evaluation beta reliability index and failure probability...
00:13:37 - Finished evaluation beta reliability index and failure probability in 1.79e-01 seconds!
00:13:37 - Voilà!!!!....simulation results were not saved in a text file!
00:13:37 - Checking inputs completed!
00:13:37 - Started State Limit Function evaluation (g)...
00:13:51 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:13:51 - Started evaluation beta reliability index and failure probability...
00:13:51 - Finished evaluation beta reliability index and failure probability in 2.02e-01 seconds!
00:13:51 - Voilà!!!!....simulation results were not saved in a text file!
00:13:51 - Checking inputs completed!
00:13:51 - Started State Limit Function evaluation (g)...
00:14:04 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:14:04 - Started evaluation beta reliability index and failure probability...
00:14:04 - Finished evaluation beta reliability index and failure probability in 1.97e-01 seconds!
00:14:04 - Voilà!!!!....simulation results were not saved in a text file!
00:14:04 - Checking inputs completed!
00:14:04 - Started State Limit Function evaluation (g)...
00:14:18 - Finished State Limit Function evaluation (g) in 1.34e+01 seconds!
00:14:18 - Started evaluation beta reliability index and failure probability...
00:14:18 - Finished evaluation beta reliability index and failure probability in 2.06e-01 seconds!
00:14:18 - Voilà!!!!....simulation results were not saved in a text file!
00:14:18 - Checking inputs completed!
00:14:18 - Started State Limit Function evaluation (g)...
00:14:32 - Finished State Limit Function evaluation (g) in 1.34e+01 seconds!
00:14:32 - Started evaluation beta reliability index and failure probability...
00:14:32 - Finished evaluation beta reliability index and failure probability in 7.03e-02 seconds!
00:14:32 - Voilà!!!!....simulation results were not saved in a text file!
00:14:32 - Checking inputs completed!
00:14:32 - Started State Limit Function evaluation (g)...
00:14:45 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:14:45 - Started evaluation beta reliability index and failure probability...
00:14:45 - Finished evaluation beta reliability index and failure probability in 1.76e-01 seconds!
00:14:45 - Voilà!!!!....simulation results were not saved in a text file!
00:14:45 - Checking inputs completed!
00:14:45 - Started State Limit Function evaluation (g)...
00:14:58 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:14:58 - Started evaluation beta reliability index and failure probability...
00:14:59 - Finished evaluation beta reliability index and failure probability in 1.81e-01 seconds!
00:14:59 - Voilà!!!!....simulation results were not saved in a text file!
00:14:59 - Checking inputs completed!
00:14:59 - Started State Limit Function evaluation (g)...
00:15:12 - Finished State Limit Function evaluation (g) in 1.34e+01 seconds!
00:15:12 - Started evaluation beta reliability index and failure probability...
00:15:12 - Finished evaluation beta reliability index and failure probability in 1.85e-01 seconds!
00:15:12 - Voilà!!!!....simulation results were not saved in a text file!
00:15:12 - Checking inputs completed!
00:15:12 - Started State Limit Function evaluation (g)...
00:15:26 - Finished State Limit Function evaluation (g) in 1.32e+01 seconds!
00:15:26 - Started evaluation beta reliability index and failure probability...
00:15:26 - Finished evaluation beta reliability index and failure probability in 1.78e-01 seconds!
00:15:26 - Voilà!!!!....simulation results were not saved in a text file!
00:15:26 - Checking inputs completed!
00:15:26 - Started State Limit Function evaluation (g)...
00:15:39 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:15:39 - Started evaluation beta reliability index and failure probability...
00:15:39 - Finished evaluation beta reliability index and failure probability in 1.13e-01 seconds!
00:15:39 - Voilà!!!!....simulation results were not saved in a text file!
00:15:39 - Checking inputs completed!
00:15:39 - Started State Limit Function evaluation (g)...
00:15:53 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:15:53 - Started evaluation beta reliability index and failure probability...
00:15:53 - Finished evaluation beta reliability index and failure probability in 1.75e-01 seconds!
00:15:53 - Voilà!!!!....simulation results were not saved in a text file!
00:15:53 - Checking inputs completed!
00:15:53 - Started State Limit Function evaluation (g)...
00:16:06 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:16:06 - Started evaluation beta reliability index and failure probability...
00:16:06 - Finished evaluation beta reliability index and failure probability in 1.90e-01 seconds!
00:16:06 - Voilà!!!!....simulation results were not saved in a text file!
00:16:06 - Checking inputs completed!
00:16:06 - Started State Limit Function evaluation (g)...
00:16:20 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:16:20 - Started evaluation beta reliability index and failure probability...
00:16:20 - Finished evaluation beta reliability index and failure probability in 2.01e-01 seconds!
00:16:20 - Voilà!!!!....simulation results were not saved in a text file!
00:16:20 - Checking inputs completed!
00:16:20 - Started State Limit Function evaluation (g)...
00:16:33 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:16:33 - Started evaluation beta reliability index and failure probability...
00:16:33 - Finished evaluation beta reliability index and failure probability in 1.78e-01 seconds!
00:16:33 - Voilà!!!!....simulation results were not saved in a text file!
00:16:33 - Checking inputs completed!
00:16:33 - Started State Limit Function evaluation (g)...
00:16:47 - Finished State Limit Function evaluation (g) in 1.34e+01 seconds!
00:16:47 - Started evaluation beta reliability index and failure probability...
00:16:47 - Finished evaluation beta reliability index and failure probability in 9.97e-02 seconds!
00:16:47 - Voilà!!!!....simulation results were not saved in a text file!
00:16:47 - Checking inputs completed!
00:16:47 - Started State Limit Function evaluation (g)...
00:17:00 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:17:00 - Started evaluation beta reliability index and failure probability...
00:17:00 - Finished evaluation beta reliability index and failure probability in 1.77e-01 seconds!
00:17:00 - Voilà!!!!....simulation results were not saved in a text file!
00:17:01 - Checking inputs completed!
00:17:01 - Started State Limit Function evaluation (g)...
00:17:14 - Finished State Limit Function evaluation (g) in 1.34e+01 seconds!
00:17:14 - Started evaluation beta reliability index and failure probability...
00:17:14 - Finished evaluation beta reliability index and failure probability in 1.92e-01 seconds!
00:17:14 - Voilà!!!!....simulation results were not saved in a text file!
00:17:14 - Checking inputs completed!
00:17:14 - Started State Limit Function evaluation (g)...
00:17:27 - Finished State Limit Function evaluation (g) in 1.32e+01 seconds!
00:17:27 - Started evaluation beta reliability index and failure probability...
00:17:28 - Finished evaluation beta reliability index and failure probability in 1.92e-01 seconds!
00:17:28 - Voilà!!!!....simulation results were not saved in a text file!
00:17:28 - Checking inputs completed!
00:17:28 - Started State Limit Function evaluation (g)...
00:17:41 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:17:41 - Started evaluation beta reliability index and failure probability...
00:17:41 - Finished evaluation beta reliability index and failure probability in 1.95e-01 seconds!
00:17:41 - Voilà!!!!....simulation results were not saved in a text file!
00:17:41 - Checking inputs completed!
00:17:41 - Started State Limit Function evaluation (g)...
00:17:54 - Finished State Limit Function evaluation (g) in 1.32e+01 seconds!
00:17:54 - Started evaluation beta reliability index and failure probability...
00:17:55 - Finished evaluation beta reliability index and failure probability in 1.44e-01 seconds!
00:17:55 - Voilà!!!!....simulation results were not saved in a text file!
00:17:55 - Checking inputs completed!
00:17:55 - Started State Limit Function evaluation (g)...
00:18:08 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:18:08 - Started evaluation beta reliability index and failure probability...
00:18:08 - Finished evaluation beta reliability index and failure probability in 1.78e-01 seconds!
00:18:08 - Voilà!!!!....simulation results were not saved in a text file!
00:18:08 - Checking inputs completed!
00:18:08 - Started State Limit Function evaluation (g)...
00:18:22 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:18:22 - Started evaluation beta reliability index and failure probability...
00:18:22 - Finished evaluation beta reliability index and failure probability in 1.75e-01 seconds!
00:18:22 - Voilà!!!!....simulation results were not saved in a text file!
00:18:22 - Checking inputs completed!
00:18:22 - Started State Limit Function evaluation (g)...
00:18:35 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:18:35 - Started evaluation beta reliability index and failure probability...
00:18:35 - Finished evaluation beta reliability index and failure probability in 2.13e-01 seconds!
00:18:35 - Voilà!!!!....simulation results were not saved in a text file!
00:18:35 - Checking inputs completed!
00:18:35 - Started State Limit Function evaluation (g)...
00:18:49 - Finished State Limit Function evaluation (g) in 1.34e+01 seconds!
00:18:49 - Started evaluation beta reliability index and failure probability...
00:18:49 - Finished evaluation beta reliability index and failure probability in 1.96e-01 seconds!
00:18:49 - Voilà!!!!....simulation results were not saved in a text file!
00:18:49 - Checking inputs completed!
00:18:49 - Started State Limit Function evaluation (g)...
00:19:02 - Finished State Limit Function evaluation (g) in 1.34e+01 seconds!
00:19:02 - Started evaluation beta reliability index and failure probability...
00:19:02 - Finished evaluation beta reliability index and failure probability in 1.54e-01 seconds!
00:19:02 - Voilà!!!!....simulation results were not saved in a text file!
00:19:02 - Checking inputs completed!
00:19:02 - Started State Limit Function evaluation (g)...
00:19:16 - Finished State Limit Function evaluation (g) in 1.33e+01 seconds!
00:19:16 - Started evaluation beta reliability index and failure probability...
00:19:16 - Finished evaluation beta reliability index and failure probability in 1.68e-01 seconds!

In [7]:
final_df.to_excel("final_df_tempo_limite.xlsx", index=False)

In [8]:
final_df.head(20)

     b_w    h     f_ck       m_rd       m_gk       m_qk       a_s       time
0   0.14  0.3  20000.0   9.836582   6.323517   0.702613  0.000076  47.180765
1   0.14  0.3  20000.0   9.836582   5.445251   1.580879  0.000076  64.788961
2   0.14  0.3  20000.0   9.836582   4.566984   2.459145  0.000076  72.239461
3   0.14  0.3  20000.0   9.836582   3.688718   3.337412  0.000076  76.586850
4   0.14  0.3  20000.0   9.836582   2.810452   4.215678  0.000076  78.950605
5   0.14  0.3  20000.0  18.823519  12.100834   1.344537  0.000152  52.053289
6   0.14  0.3  20000.0  18.823519  10.420163   3.025208  0.000152  64.496821
7   0.14  0.3  20000.0  18.823519   8.739491   4.705880  0.000152  73.799074
8   0.14  0.3  20000.0  18.823519   7.058820   6.386551  0.000152  78.193143
9   0.14  0.3  20000.0  18.823519   5.378148   8.067223  0.000152  80.940341
10  0.14  0.3  20000.0  26.960813  17.331951   1.925772  0.000228  54.252989
11  0.14  0.3  20000.0  26.960813  14.924736   4.332988  0.000228  66.905583
12  0.14  0.3  20000.0  26.960813  12.517520   6.740203  0.000228  74.261961
13  0.14  0.3  20000.0  26.960813  10.110305   9.147419  0.000228  80.318928
14  0.14  0.3  20000.0  26.960813   7.703089  11.554634  0.000228  82.597665
15  0.14  0.3  20000.0  34.248462  22.016868   2.446319  0.000304  55.453305
16  0.14  0.3  20000.0  34.248462  18.958970   5.504217  0.000304  66.945580
17  0.14  0.3  20000.0  34.248462  15.901072   8.562115  0.000304  75.554178
18  0.14  0.3  20000.0  34.248462  12.843173  11.620014  0.000304  80.680025
19  0.14  0.3  20000.0  34.248462   9.785275  14.677912  0.000304  83.410829